# # Generated by Django 4.2.2 on 2023-06-12 11:20
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#     initial = True
#
#     dependencies = []
#
#     operations = [
#         migrations.CreateModel(
#             name="Artwork",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("title", models.CharField(max_length=255)),
#                 ("image_url", models.URLField()),
#                 ("description", models.TextField()),
#                 ("price", models.DecimalField(decimal_places=2, max_digits=10)),
#             ],
#         ),
#         migrations.CreateModel(
#             name="Medium",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("name", models.CharField(max_length=255)),
#             ],
#         ),
#         migrations.CreateModel(
#             name="Style",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("name", models.CharField(max_length=255)),
#             ],
#         ),
#     ]


# Generated by Django 4.2.2 on 2023-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Medium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
