# Generated by Django 4.1.7 on 2023-07-14 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gallery_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="gallery_app.artist",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="gallery_app.category",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_artworks",
                through="gallery_app.Like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="categories",
            field=models.ManyToManyField(to="gallery_app.category"),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "artwork")},
        ),
    ]
