# # Generated by Django 4.2.2 on 2023-06-12 11:20
#
# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
#
#
# class Migration(migrations.Migration):
#     initial = True
#
#     dependencies = [
#         ("user", "0001_initial"),
#         ("gallery_app", "0001_initial"),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]
#
#     operations = [
#         migrations.AddField(
#             model_name="artwork",
#             name="artist",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="artworks",
#                 to="user.artist",
#             ),
#         ),
#         migrations.AddField(
#             model_name="artwork",
#             name="likes",
#             field=models.ManyToManyField(
#                 blank=True, related_name="liked_artworks", to=settings.AUTH_USER_MODEL
#             ),
#         ),
#         migrations.AddField(
#             model_name="artwork",
#             name="medium",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="artworks",
#                 to="gallery_app.medium",
#             ),
#         ),
#         migrations.AddField(
#             model_name="artwork",
#             name="style",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="artworks",
#                 to="gallery_app.style",
#             ),
#         ),
#     ]

# Generated by Django 4.2.2 on 2023-06-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("gallery_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="user.artist",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_artworks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="medium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="gallery_app.medium",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="gallery_app.style",
            ),
        ),
    ]
