# Generated by Django 4.2.2 on 2023-06-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_app", "0003_artist_alter_artwork_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PAINTING", "Painting"),
                            ("PHOTOGRAPHY", "Photography"),
                            ("SCULPTURE", "Sculpture"),
                            ("PRINTS", "Prints"),
                            ("WORK_ON_PAPER", "Work on paper"),
                            ("DESIGN", "Design"),
                            ("GRAPHIC_DESIGN", "Graphic design"),
                            ("COLLAGES", "Collages"),
                            ("ILLUSTRATION", "Illustration"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="artist",
            name="mediums",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="medium",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="style",
        ),
        migrations.AddField(
            model_name="artwork",
            name="color",
            field=models.CharField(
                choices=[
                    ("BEIGE", "Beige"),
                    ("BLACK", "Black"),
                    ("BLUE", "Blue"),
                    ("BROWN", "Brown"),
                    ("GOLD", "Gold"),
                    ("GREEN", "Green"),
                    ("GREY", "Grey"),
                    ("ORANGE", "Orange"),
                    ("PINK", "Pink"),
                    ("PURPLE", "Purple"),
                    ("RED", "Red"),
                    ("SILVER", "Silver"),
                    ("WHITE", "White"),
                    ("YELLOW", "Yellow"),
                    ("MULTI", "Multi"),
                    ("BLACK_AND_WHITE", "Black & White"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Medium",
        ),
        migrations.DeleteModel(
            name="Style",
        ),
        migrations.AddField(
            model_name="artist",
            name="categories",
            field=models.ManyToManyField(to="gallery_app.category"),
        ),
        migrations.AddField(
            model_name="artwork",
            name="categories",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="gallery_app.category",
            ),
            preserve_default=False,
        ),
    ]
