# Generated by Django 4.2.2 on 2023-06-14 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_app", "0002_initial"),
        (
            "gallery_app",
            "0004_category_remove_artist_mediums_remove_artwork_medium_and_more",
        ),
    ]

    operations = []
