# Generated by Django 4.2.2 on 2023-07-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_app", "0006_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                default="https://onlinegallery.art/images/profiles/portret-geert-met-schilderij.jpg?type=webp",
                upload_to="",
            ),
        ),
    ]
