# Generated by Django 4.1.7 on 2023-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_app", "0008_alter_artist_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="year",
            field=models.IntegerField(default=2005),
        ),
    ]
