# Generated by Django 4.1.7 on 2023-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0009_artwork_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(),
        ),
    ]
