# Generated by Django 4.2.2 on 2023-06-12 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery_app", "0003_artist_alter_artwork_artist"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
